### ISSUE TITLE
pip v1.4

### ISSUE THREAD

**Issue by mdave16** [videlec/pypolymake#7]
As you probably know, pip got updated.
one of the features is to only install stable versions, unless specified

`pip install pypolymake --pre`

the --pre let's you install beta versions. Just spent an hour trying to install this and found out about this.
Could you put it in the README?

EDIT:

also I kept seeing this error when trying to install, I'm basically going to keep trying to install and report any errors here.

`cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++`

I know neither of these are big, but felt i should report them still.

**Comment by videlec** [comment]
Thanks for your report.

I mentioned `--pre` in the README.

For the compilation warning, this is probably due to Cython. I am not sure I can tweak that in setup.py.

**Comment by mdave16** [comment]
just realised i hadn't closed this -- thanks for all the work :)
