### ISSUE TITLE
pylong.c not found

### ISSUE THREAD

**Issue by mmasdeu** [videlec/pypolymake#8]
Hi, Vincent, nice work!

I am trying to use pypolymake from within Sage. When compiling as per your instructions (python2 setup.py install --user) I get the following:

`gcc: error: src/cygmp/pylong.c: No such file or directory`
`gcc: fatal error: no input files`

I fixed it (and managed to compile) by copying this file from my Sage installation.

**Comment by videlec** [comment]
Thanks. Indeed, this file is not needed at all. It is a problem in setup.py

**Comment by videlec** [comment]
Fixed in afee34a
